### ISSUE TITLE
Need better Page 211

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon-scans/md#1]
The image https://github.com/sanskrit-lexicon-scans/md/blob/gh-pages/pdfpages/pg_211.jpg
has missing data in top of first column. 

**We need a new image file**.

This is under headword 'Bos', and the digitization looks correct in this detail (i.e., Thomas
must have used a better image when his staff prepared the digitization).

https://www.sanskrit-lexicon.uni-koeln.de/simple/md/Bos

**Comment by funderburkjim** [comment]
Checked with Thomas - He does not currently have a better image.

**Comment by Andhrabharati** [comment]
Will this work @funderburkjim, to close the issue?

![MD-211](https://user-images.githubusercontent.com/75209130/176407124-0a111569-6c87-48fe-b578-b2cd92a1aaec.jpg)

**Comment by drdhaval2785** [comment]
@funderburkjim Time to install this and close?

**Comment by funderburkjim** [comment]
Yes.

 New pg_211.jpg for md installed both at Cologne and at github/sanskrit-lexicon/scans/md
